# Use postgres/example user/password credentials
version: '4.1'

services:
  web:
    image: minder-api:latest
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - postgres
      - pgadmin
      - filezilla
    networks:
      network:
        ipv4_address: 172.40.0.2
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=VanToan
      - POSTGRES_PASSWORD=Ltvh_2912
      - POSTGRES_DB=Minder
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: 3
    networks:
      network:
        ipv4_address: 172.40.0.3
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=toan01473@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=hovantoan
    ports:
      - "25000:80"
    networks:
      network:
        ipv4_address: 172.40.0.4
  filezilla:
    image: jlesage/filezilla
    ports:
      - "8081:5800"
    networks:
      network:
        ipv4_address: 172.40.0.5
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16
          gateway: 172.40.0.1

